### ISSUE TITLE
Aborting acsf-setup.sh has incorrect messages 

### ISSUE THREAD

**Issue by eolienne** [SU-SWS/acsf_setup#3]
`

Are you ready to proceed? (Y/N): N
Aborting. Run away!

Site setup complete. Go to https://facultysurvey.sites.stanford.edu to verify setup.

Wait 3-8 minutes for SAML authentication to work.`

When we opt _not_ to proceed, there shouldn't be any messages like "Site setup complete..."

**Comment by jbickar** [comment]
Should be fixed now
